import imageResource from './client/resources/images';

// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    id: 1,
    name: 'Science',
    articles: [
      {
        id: 1,
        title: 'US offers $10m bounty for Colonial Pipeline hackers',
        authorImage: imageResource.authors.ziggy,
        author: 'Ziggy',
        date: '01/01/2021',
        minutes: '10',
        thumbnail: imageResource.technologyThumbnails.T1,
        image: '',
        content:
          '$10m is the largest bounty ever offered for the arrest of a specific cyber-criminal.The ignominious record was previously held by Maksim Yakubets, the alleged mastermind behind another ransomware gang called Evil Corp.The US named and shamed him (along with help from the UK authorities) in 2019.Before that, the record bounty stood at $3m for another alleged cyber-crime boss called Evgeniy Bogachev.The thing these individuals have in common? They are thought to be living care-free lives in Russia safe from any prospect of arrest from the local police, who routinely ignore western accusations against Russian hackers.Even with their names, pictures and a rough location published by the US, these alleged criminals are safe.The US seems to have even less to go on in terms of unmasking DarkSides leaders, although most research suggests they are also in Russia.So, despite the eye-watering sums being offered by the US, the chances of these criminals facing justice are slim.',
        tags: 'United States, Oil & Gas industry, Cyber-security',
        claps: '9.3',
      },
      {
        id: 2,
        title: 'Zuckerberg metaverse: Lessons from Second Life',
        authorImage: imageResource.authors.cookie,
        author: 'Cookie',
        date: '02/01/2021',
        minutes: '15',
        thumbnail: imageResource.technologyThumbnails.T2,
        image: '',
        content:
          'This week, I travelled back in time to visit the future.It has been about 10 years since I first entered the virtual world of Second Life, arguably the internets first attempt at what every tech giant is now racing to build: the so-called metaverse.The term metaverse was coined in the 1990s in a science-fiction novel, Snow Crash, where it served as a virtual-reality successor to the internet, where people live large portions of their lives in virtual environments.Second Life peaked in the late 2000s with millions of users and hundreds of excitable headlines about people devoting hours of their daily lives to live digitally.Since then, I assumed it had died a slow and quiet death. But how wrong I was.The platform seems to have a small, loyal and potentially growing community of "residents", as they call themselves, logging on to experience what our metaverse future could look like.So for this weeks Tech Tent podcast, I dipped back in.',
        tags: 'Gaming, Mark Zuckerberg, Facebook',
        claps: '4.5',
      },
      {
        id: 3,
        title: 'Instagram post previews to return on Twitter',
        authorImage: imageResource.authors.ziggy,
        author: 'Ziggy',
        date: '03/01/2021',
        minutes: '15',
        thumbnail: imageResource.technologyThumbnails.T3,
        image: '',
        content:
          'Instagram has brought back support for Twitter card previews after removing the feature nine years ago. Now, when users share an Instagram link on Twitter, a small preview of the post will be displayed.Instagram controversially removed the feature shortly after being acquired by Facebook in 2012.Twitter card previews started for some users on Wednesday and will eventually be available to everyone. Instagram and Twitter are both promoting the change.',
        tags: 'Instagram, Twitter',
        claps: '3.7',
      },
      {
        id: 4,
        title: 'NYC next mayor wants to be paid in Bitcoin',
        authorImage: imageResource.authors.ziggy,
        author: 'Ziggy',
        date: '04/01/2021',
        minutes: '10',
        thumbnail: imageResource.technologyThumbnails.T4,
        image: '',
        content:
          'The former police captain was elected this week to take over at the end of mayor Bill de Blasios term in January. Mr Adams said on social media that he wanted to signal his intention to make New York the "centre of the cryptocurrency industry".The value of bitcoin, the worlds largest cryptocurrency, has been highly volatile, since it was created in 2009. Mr Adam comments appear to be an attempt to one-up the mayor of Miami, Francis Suarez, who had already said in his own Twitter message that he would take his first pay check in bitcoin, after he was re-elected. Mr Suarez has already said he would like to establish Miami as a hub for cryptocurrency innovation. Mr Adams upped the stakes by asking for three months pay in the cryptocurrency.',
        tags: 'Bitcoin, New York City, Cryptocurrency',
        claps: '8.7',
      },
    ],
  },
  {
    id: 2,
    name: 'Technology',
    tolink: '/technology',
    articles: [
      {
        id: 1,
        title: 'US offers $10m bounty for Colonial Pipeline hackers',
        authorImage: imageResource.authors.ziggy,
        author: 'Ziggy',
        date: '01/01/2021',
        minutes: '10',
        thumbnail: imageResource.technologyThumbnails.T1,
        image: '',
        content:
          '$10m is the largest bounty ever offered for the arrest of a specific cyber-criminal.The ignominious record was previously held by Maksim Yakubets, the alleged mastermind behind another ransomware gang called Evil Corp.The US named and shamed him (along with help from the UK authorities) in 2019.Before that, the record bounty stood at $3m for another alleged cyber-crime boss called Evgeniy Bogachev.The thing these individuals have in common? They are thought to be living care-free lives in Russia safe from any prospect of arrest from the local police, who routinely ignore western accusations against Russian hackers.Even with their names, pictures and a rough location published by the US, these alleged criminals are safe.The US seems to have even less to go on in terms of unmasking DarkSides leaders, although most research suggests they are also in Russia.So, despite the eye-watering sums being offered by the US, the chances of these criminals facing justice are slim.',
        tags: 'United States, Oil & Gas industry, Cyber-security',
        claps: '9.3',
      },
      {
        id: 2,
        title: 'Zuckerberg metaverse: Lessons from Second Life',
        authorImage: imageResource.authors.cookie,
        author: 'Cookie',
        date: '02/01/2021',
        minutes: '15',
        thumbnail: imageResource.technologyThumbnails.T2,
        image: '',
        content:
          'This week, I travelled back in time to visit the future.It has been about 10 years since I first entered the virtual world of Second Life, arguably the internets first attempt at what every tech giant is now racing to build: the so-called metaverse.The term metaverse was coined in the 1990s in a science-fiction novel, Snow Crash, where it served as a virtual-reality successor to the internet, where people live large portions of their lives in virtual environments.Second Life peaked in the late 2000s with millions of users and hundreds of excitable headlines about people devoting hours of their daily lives to live digitally.Since then, I assumed it had died a slow and quiet death. But how wrong I was.The platform seems to have a small, loyal and potentially growing community of "residents", as they call themselves, logging on to experience what our metaverse future could look like.So for this weeks Tech Tent podcast, I dipped back in.',
        tags: 'Gaming, Mark Zuckerberg, Facebook',
        claps: '4.5',
      },
      {
        id: 3,
        title: 'Instagram post previews to return on Twitter',
        authorImage: imageResource.authors.ziggy,
        author: 'Ziggy',
        date: '03/01/2021',
        minutes: '15',
        thumbnail: imageResource.technologyThumbnails.T3,
        image: '',
        content:
          'Instagram has brought back support for Twitter card previews after removing the feature nine years ago. Now, when users share an Instagram link on Twitter, a small preview of the post will be displayed.Instagram controversially removed the feature shortly after being acquired by Facebook in 2012.Twitter card previews started for some users on Wednesday and will eventually be available to everyone. Instagram and Twitter are both promoting the change.',
        tags: 'Instagram, Twitter',
        claps: '3.7',
      },
      {
        id: 4,
        title: 'NYC next mayor wants to be paid in Bitcoin',
        authorImage: imageResource.authors.ziggy,
        author: 'Ziggy',
        date: '04/01/2021',
        minutes: '10',
        thumbnail: imageResource.technologyThumbnails.T4,
        image: '',
        content:
          'The former police captain was elected this week to take over at the end of mayor Bill de Blasios term in January. Mr Adams said on social media that he wanted to signal his intention to make New York the "centre of the cryptocurrency industry".The value of bitcoin, the worlds largest cryptocurrency, has been highly volatile, since it was created in 2009. Mr Adam comments appear to be an attempt to one-up the mayor of Miami, Francis Suarez, who had already said in his own Twitter message that he would take his first pay check in bitcoin, after he was re-elected. Mr Suarez has already said he would like to establish Miami as a hub for cryptocurrency innovation. Mr Adams upped the stakes by asking for three months pay in the cryptocurrency.',
        tags: 'Bitcoin, New York City, Cryptocurrency',
        claps: '8.7',
      },
    ],
  },
  {
    id: 3,
    name: 'Movies',
    tolink: '/movies',
    articles: [
      {
        id: 1,
        title: 'US offers $10m bounty for Colonial Pipeline hackers',
        authorImage: imageResource.authors.ziggy,
        author: 'Ziggy',
        date: '01/01/2021',
        minutes: '10',
        thumbnail: imageResource.technologyThumbnails.T1,
        image: '',
        content:
          '$10m is the largest bounty ever offered for the arrest of a specific cyber-criminal.The ignominious record was previously held by Maksim Yakubets, the alleged mastermind behind another ransomware gang called Evil Corp.The US named and shamed him (along with help from the UK authorities) in 2019.Before that, the record bounty stood at $3m for another alleged cyber-crime boss called Evgeniy Bogachev.The thing these individuals have in common? They are thought to be living care-free lives in Russia safe from any prospect of arrest from the local police, who routinely ignore western accusations against Russian hackers.Even with their names, pictures and a rough location published by the US, these alleged criminals are safe.The US seems to have even less to go on in terms of unmasking DarkSides leaders, although most research suggests they are also in Russia.So, despite the eye-watering sums being offered by the US, the chances of these criminals facing justice are slim.',
        tags: 'United States, Oil & Gas industry, Cyber-security',
        claps: '9.3',
      },
      {
        id: 2,
        title: 'Zuckerberg metaverse: Lessons from Second Life',
        authorImage: imageResource.authors.cookie,
        author: 'Cookie',
        date: '02/01/2021',
        minutes: '15',
        thumbnail: imageResource.technologyThumbnails.T2,
        image: '',
        content:
          'This week, I travelled back in time to visit the future.It has been about 10 years since I first entered the virtual world of Second Life, arguably the internets first attempt at what every tech giant is now racing to build: the so-called metaverse.The term metaverse was coined in the 1990s in a science-fiction novel, Snow Crash, where it served as a virtual-reality successor to the internet, where people live large portions of their lives in virtual environments.Second Life peaked in the late 2000s with millions of users and hundreds of excitable headlines about people devoting hours of their daily lives to live digitally.Since then, I assumed it had died a slow and quiet death. But how wrong I was.The platform seems to have a small, loyal and potentially growing community of "residents", as they call themselves, logging on to experience what our metaverse future could look like.So for this weeks Tech Tent podcast, I dipped back in.',
        tags: 'Gaming, Mark Zuckerberg, Facebook',
        claps: '4.5',
      },
      {
        id: 3,
        title: 'Instagram post previews to return on Twitter',
        authorImage: imageResource.authors.ziggy,
        author: 'Ziggy',
        date: '02/01/2021',
        minutes: '15',
        thumbnail: imageResource.technologyThumbnails.T3,
        image: '',
        content:
          'Instagram has brought back support for Twitter card previews after removing the feature nine years ago. Now, when users share an Instagram link on Twitter, a small preview of the post will be displayed.Instagram controversially removed the feature shortly after being acquired by Facebook in 2012.Twitter card previews started for some users on Wednesday and will eventually be available to everyone. Instagram and Twitter are both promoting the change.',
        tags: 'Instagram, Twitter',
        claps: '3.7',
      },
      {
        id: 4,
        title: 'NYC next mayor wants to be paid in Bitcoin',
        authorImage: imageResource.authors.ziggy,
        author: 'Ziggy',
        date: '04/01/2021',
        minutes: '10',
        thumbnail: imageResource.technologyThumbnails.T4,
        image: '',
        content:
          'The former police captain was elected this week to take over at the end of mayor Bill de Blasios term in January. Mr Adams said on social media that he wanted to signal his intention to make New York the "centre of the cryptocurrency industry".The value of bitcoin, the worlds largest cryptocurrency, has been highly volatile, since it was created in 2009. Mr Adam comments appear to be an attempt to one-up the mayor of Miami, Francis Suarez, who had already said in his own Twitter message that he would take his first pay check in bitcoin, after he was re-elected. Mr Suarez has already said he would like to establish Miami as a hub for cryptocurrency innovation. Mr Adams upped the stakes by asking for three months pay in the cryptocurrency.',
        tags: 'Bitcoin, New York City, Cryptocurrency',
        claps: '8.7',
      },
    ],
  },
  {
    id: 4,
    name: 'Fitness',
    tolink: '/fitness',
    articles: [
      {
        id: 1,
        title: 'US offers $10m bounty for Colonial Pipeline hackers',
        authorImage: imageResource.authors.ziggy,
        author: 'Ziggy',
        date: '01/01/2021',
        minutes: '10',
        thumbnail: imageResource.technologyThumbnails.T1,
        image: '',
        content:
          '$10m is the largest bounty ever offered for the arrest of a specific cyber-criminal.The ignominious record was previously held by Maksim Yakubets, the alleged mastermind behind another ransomware gang called Evil Corp.The US named and shamed him (along with help from the UK authorities) in 2019.Before that, the record bounty stood at $3m for another alleged cyber-crime boss called Evgeniy Bogachev.The thing these individuals have in common? They are thought to be living care-free lives in Russia safe from any prospect of arrest from the local police, who routinely ignore western accusations against Russian hackers.Even with their names, pictures and a rough location published by the US, these alleged criminals are safe.The US seems to have even less to go on in terms of unmasking DarkSides leaders, although most research suggests they are also in Russia.So, despite the eye-watering sums being offered by the US, the chances of these criminals facing justice are slim.',
        tags: 'United States, Oil & Gas industry, Cyber-security',
        claps: '9.3',
      },
      {
        id: 2,
        title: 'Zuckerberg metaverse: Lessons from Second Life',
        authorImage: imageResource.authors.cookie,
        author: 'Cookie',
        date: '02/01/2021',
        minutes: '15',
        thumbnail: imageResource.technologyThumbnails.T2,
        image: '',
        content:
          'This week, I travelled back in time to visit the future.It has been about 10 years since I first entered the virtual world of Second Life, arguably the internets first attempt at what every tech giant is now racing to build: the so-called metaverse.The term metaverse was coined in the 1990s in a science-fiction novel, Snow Crash, where it served as a virtual-reality successor to the internet, where people live large portions of their lives in virtual environments.Second Life peaked in the late 2000s with millions of users and hundreds of excitable headlines about people devoting hours of their daily lives to live digitally.Since then, I assumed it had died a slow and quiet death. But how wrong I was.The platform seems to have a small, loyal and potentially growing community of "residents", as they call themselves, logging on to experience what our metaverse future could look like.So for this weeks Tech Tent podcast, I dipped back in.',
        tags: 'Gaming, Mark Zuckerberg, Facebook',
        claps: '4.5',
      },
      {
        id: 3,
        title: 'Instagram post previews to return on Twitter',
        authorImage: imageResource.authors.ziggy,
        author: 'Ziggy',
        date: '02/01/2021',
        minutes: '15',
        thumbnail: imageResource.technologyThumbnails.T3,
        image: '',
        content:
          'Instagram has brought back support for Twitter card previews after removing the feature nine years ago. Now, when users share an Instagram link on Twitter, a small preview of the post will be displayed.Instagram controversially removed the feature shortly after being acquired by Facebook in 2012.Twitter card previews started for some users on Wednesday and will eventually be available to everyone. Instagram and Twitter are both promoting the change.',
        tags: 'Instagram, Twitter',
        claps: '3.7',
      },
      {
        id: 4,
        title: 'NYC next mayor wants to be paid in Bitcoin',
        authorImage: imageResource.authors.ziggy,
        author: 'Ziggy',
        date: '04/01/2021',
        minutes: '10',
        thumbnail: imageResource.technologyThumbnails.T4,
        image: '',
        content:
          'The former police captain was elected this week to take over at the end of mayor Bill de Blasios term in January. Mr Adams said on social media that he wanted to signal his intention to make New York the "centre of the cryptocurrency industry".The value of bitcoin, the worlds largest cryptocurrency, has been highly volatile, since it was created in 2009. Mr Adam comments appear to be an attempt to one-up the mayor of Miami, Francis Suarez, who had already said in his own Twitter message that he would take his first pay check in bitcoin, after he was re-elected. Mr Suarez has already said he would like to establish Miami as a hub for cryptocurrency innovation. Mr Adams upped the stakes by asking for three months pay in the cryptocurrency.',
        tags: 'Bitcoin, New York City, Cryptocurrency',
        claps: '8.7',
      },
    ],
  },
  {
    id: 5,
    name: 'Food',
    tolink: '/food',
    articles: [
      {
        id: 1,
        title: 'US offers $10m bounty for Colonial Pipeline hackers',
        authorImage: imageResource.authors.ziggy,
        author: 'Ziggy',
        date: '01/01/2021',
        minutes: '10',
        thumbnail: imageResource.technologyThumbnails.T1,
        image: '',
        content:
          '$10m is the largest bounty ever offered for the arrest of a specific cyber-criminal.The ignominious record was previously held by Maksim Yakubets, the alleged mastermind behind another ransomware gang called Evil Corp.The US named and shamed him (along with help from the UK authorities) in 2019.Before that, the record bounty stood at $3m for another alleged cyber-crime boss called Evgeniy Bogachev.The thing these individuals have in common? They are thought to be living care-free lives in Russia safe from any prospect of arrest from the local police, who routinely ignore western accusations against Russian hackers.Even with their names, pictures and a rough location published by the US, these alleged criminals are safe.The US seems to have even less to go on in terms of unmasking DarkSides leaders, although most research suggests they are also in Russia.So, despite the eye-watering sums being offered by the US, the chances of these criminals facing justice are slim.',
        tags: 'United States, Oil & Gas industry, Cyber-security',
        claps: '9.3',
      },
      {
        id: 2,
        title: 'Zuckerberg metaverse: Lessons from Second Life',
        authorImage: imageResource.authors.cookie,
        author: 'Cookie',
        date: '02/01/2021',
        minutes: '15',
        thumbnail: imageResource.technologyThumbnails.T2,
        image: '',
        content:
          'This week, I travelled back in time to visit the future.It has been about 10 years since I first entered the virtual world of Second Life, arguably the internets first attempt at what every tech giant is now racing to build: the so-called metaverse.The term metaverse was coined in the 1990s in a science-fiction novel, Snow Crash, where it served as a virtual-reality successor to the internet, where people live large portions of their lives in virtual environments.Second Life peaked in the late 2000s with millions of users and hundreds of excitable headlines about people devoting hours of their daily lives to live digitally.Since then, I assumed it had died a slow and quiet death. But how wrong I was.The platform seems to have a small, loyal and potentially growing community of "residents", as they call themselves, logging on to experience what our metaverse future could look like.So for this weeks Tech Tent podcast, I dipped back in.',
        tags: 'Gaming, Mark Zuckerberg, Facebook',
        claps: '4.5',
      },
      {
        id: 3,
        title: 'Instagram post previews to return on Twitter',
        authorImage: imageResource.authors.ziggy,
        author: 'Ziggy',
        date: '02/01/2021',
        minutes: '15',
        thumbnail: imageResource.technologyThumbnails.T3,
        image: '',
        content:
          'Instagram has brought back support for Twitter card previews after removing the feature nine years ago. Now, when users share an Instagram link on Twitter, a small preview of the post will be displayed.Instagram controversially removed the feature shortly after being acquired by Facebook in 2012.Twitter card previews started for some users on Wednesday and will eventually be available to everyone. Instagram and Twitter are both promoting the change.',
        tags: 'Instagram, Twitter',
        claps: '3.7',
      },
      {
        id: 4,
        title: 'NYC next mayor wants to be paid in Bitcoin',
        authorImage: imageResource.authors.ziggy,
        author: 'Ziggy',
        date: '04/01/2021',
        minutes: '10',
        thumbnail: imageResource.technologyThumbnails.T4,
        image: '',
        content:
          'The former police captain was elected this week to take over at the end of mayor Bill de Blasios term in January. Mr Adams said on social media that he wanted to signal his intention to make New York the "centre of the cryptocurrency industry".The value of bitcoin, the worlds largest cryptocurrency, has been highly volatile, since it was created in 2009. Mr Adam comments appear to be an attempt to one-up the mayor of Miami, Francis Suarez, who had already said in his own Twitter message that he would take his first pay check in bitcoin, after he was re-elected. Mr Suarez has already said he would like to establish Miami as a hub for cryptocurrency innovation. Mr Adams upped the stakes by asking for three months pay in the cryptocurrency.',
        tags: 'Bitcoin, New York City, Cryptocurrency',
        claps: '8.7',
      },
    ],
  },
];
